// GENERATED by tools/gen-facepacks.mjs — do not edit by hand.
// Resource-only WFP face packaging for Arclight Solstice. WFF content is reused
// straight from the fablecollection submodule; only the applicationId changes.
plugins { id("com.android.application") }

android {
    namespace = "com.dialed.app.watchfacepush.arclight.solstice"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.dialed.app.watchfacepush.arclight.solstice"     // WFP rule: <marketplaceAppId>.watchfacepush.<name>
        minSdk = 33
        targetSdk = 33
        versionCode = 1
        versionName = "1.0"
    }

    // One source of truth: reuse the face's res + manifest from the submodule.
    sourceSets["main"].res.setSrcDirs(listOf("$rootDir/faces/Arclight-Solstice/app/src/main/res"))
    sourceSets["main"].manifest.srcFile("$rootDir/faces/Arclight-Solstice/app/src/main/AndroidManifest.xml")

    // Shared throwaway faces key — MUST differ from the :app signing key (WFP requirement).
    signingConfigs {
        create("faces") {
            storeFile = file("$rootDir/dialed-faces.keystore")
            storePassword = "android"
            keyAlias = "androiddebugkey"
            keyPassword = "android"
        }
    }
    // AGP 9's built-in Kotlin bundles kotlin-stdlib metadata (kotlin/*.kotlin_builtins) into
    // the APK; WFP's strict entry allowlist (AndroidManifest.xml / resources.arsc / res/** /
    // META-INF/** only) rejects the kotlin/ dir. hasCode=false means it's never used — drop it.
    packaging {
        resources {
            excludes += listOf(
                "kotlin/**",
                "**/*.kotlin_builtins",
                "META-INF/*.kotlin_module",
                "META-INF/versions/**",
                "DebugProbesKt.bin",
            )
        }
    }

    buildTypes {
        // minify MUST stay OFF: hasCode=false already yields no dex, and enabling R8 renames
        // resources (res/0I.png), breaking WFF @drawable/<name> lookups and the WFP
        // memory-footprint asset check. Matches the original fablecollection face config.
        release {
            signingConfig = signingConfigs.getByName("faces")
            isMinifyEnabled = false
        }
        debug {
            signingConfig = signingConfigs.getByName("faces")
            isMinifyEnabled = false
        }
    }
}
