// GENERATED by tools/gen-facepacks.mjs — do not edit by hand.
// Resource-only WFP face packaging for Vespera Meteorite. WFF content is reused
// straight from the fablecollection submodule; only the applicationId changes.
plugins { id("com.android.application") }

android {
    namespace = "com.dialed.app.watchfacepush.vespera.meteorite"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.dialed.app.watchfacepush.vespera.meteorite"     // WFP rule: <marketplaceAppId>.watchfacepush.<name>
        minSdk = 33
        targetSdk = 33
        versionCode = 1
        versionName = "1.0"
    }

    // One source of truth: reuse the face's res + manifest from the submodule.
    sourceSets["main"].res.setSrcDirs(listOf("$rootDir/faces/Vespera-Meteorite/app/src/main/res"))
    sourceSets["main"].manifest.srcFile("$rootDir/faces/Vespera-Meteorite/app/src/main/AndroidManifest.xml")

    // Shared throwaway faces key — MUST differ from the :app signing key (WFP requirement).
    signingConfigs {
        create("faces") {
            storeFile = file("$rootDir/dialed-faces.keystore")
            storePassword = "android"
            keyAlias = "androiddebugkey"
            keyPassword = "android"
        }
    }
    buildTypes {
        release {
            signingConfig = signingConfigs.getByName("faces")
            isMinifyEnabled = true      // strip the (empty) dex — required for WFF/WFP validity
            isShrinkResources = false
        }
        debug {
            signingConfig = signingConfigs.getByName("faces")
            isMinifyEnabled = true
        }
    }
}
