// GENERATED by tools/gen-facepacks.mjs — do not edit by hand.
// Resource-only WFP face packaging for Halo Beacon. WFF resources are copied from
// the fablecollection submodule into ./wff-res with watchface.xml patched to bare resource
// names (the memory-footprint validator can't resolve the non-canonical @drawable/ prefix).
// Only the applicationId changes vs the original face.
plugins { id("com.android.application") }

android {
    namespace = "com.dialed.app.watchfacepush.halo.beacon"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.dialed.app.watchfacepush.halo.beacon"     // WFP rule: <marketplaceAppId>.watchfacepush.<name>
        minSdk = 33
        targetSdk = 33
        versionCode = 1
        versionName = "1.0"
    }

    // res = patched copy (bare resource names); manifest reused from the submodule.
    sourceSets["main"].res.setSrcDirs(listOf("$projectDir/wff-res"))
    sourceSets["main"].manifest.srcFile("$rootDir/faces/Halo-Beacon/app/src/main/AndroidManifest.xml")

    // Shared throwaway faces key — MUST differ from the :app signing key (WFP requirement).
    signingConfigs {
        create("faces") {
            storeFile = file("$rootDir/dialed-faces.keystore")
            storePassword = "android"
            keyAlias = "androiddebugkey"
            keyPassword = "android"
        }
    }
    // AGP 9's built-in Kotlin bundles kotlin-stdlib metadata (kotlin/*.kotlin_builtins) into
    // the APK; WFP's strict entry allowlist (AndroidManifest.xml / resources.arsc / res/** /
    // META-INF/** only) rejects the kotlin/ dir. hasCode=false means it's never used — drop it.
    packaging {
        resources {
            excludes += listOf(
                "kotlin/**",
                "**/*.kotlin_builtins",
                "META-INF/*.kotlin_module",
                "META-INF/versions/**",
                "DebugProbesKt.bin",
            )
        }
    }

    buildTypes {
        // minify=true strips the (empty) classes.dex that WFP's file allowlist forbids.
        // It shortens res FILE PATHS (res/0I.png) but KEEPS resource NAMES in the arsc, and
        // the validator resolves drawables by name — so this is safe. Mirrors Google's sample.
        release {
            signingConfig = signingConfigs.getByName("faces")
            isMinifyEnabled = true
            isShrinkResources = false
        }
        debug {
            signingConfig = signingConfigs.getByName("faces")
            isMinifyEnabled = true
        }
    }
}
